/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testaudioandroid_VoiceSession */

#ifndef _Included_com_example_testaudioandroid_VoiceSession
#define _Included_com_example_testaudioandroid_VoiceSession
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_example_testaudioandroid_VoiceSession
 * Method:    Init
 * Signature: (Ljava/lang/String;S)I
 */
JNIEXPORT jint JNICALL Java_com_example_testaudioandroid_VoiceSession_Init
  (JNIEnv *, jobject, jstring, jshort);

/*
 * Class:     com_example_testaudioandroid_VoiceSession
 * Method:    Reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_testaudioandroid_VoiceSession_Reset
  (JNIEnv *, jobject);

/*
 * Class:     com_example_testaudioandroid_VoiceSession
 * Method:    LoginServer
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_testaudioandroid_VoiceSession_LoginServer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_testaudioandroid_VoiceSession
 * Method:    LoginOutServer
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_testaudioandroid_VoiceSession_LoginOutServer
  (JNIEnv *, jobject);

/*
 * Class:     com_example_testaudioandroid_VoiceSession
 * Method:    CreateRoom
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_testaudioandroid_VoiceSession_CreateRoom
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_testaudioandroid_VoiceSession
 * Method:    DestroyRoom
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_testaudioandroid_VoiceSession_DestroyRoom
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_testaudioandroid_VoiceSession
 * Method:    EnterRoom
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_testaudioandroid_VoiceSession_EnterRoom
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_testaudioandroid_VoiceSession
 * Method:    LeaveRoom
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_testaudioandroid_VoiceSession_LeaveRoom
  (JNIEnv *, jobject);

/*
 * Class:     com_example_testaudioandroid_VoiceSession
 * Method:    GetRoomList
 * Signature: (Ljava/util/ArrayList;)I
 */
JNIEXPORT jint JNICALL Java_com_example_testaudioandroid_VoiceSession_GetRoomList
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_example_testaudioandroid_VoiceSession
 * Method:    SendData
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_com_example_testaudioandroid_VoiceSession_SendData
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     com_example_testaudioandroid_VoiceSession
 * Method:    SetRecvData
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_com_example_testaudioandroid_VoiceSession_SetRecvData
  (JNIEnv *, jobject, jint, jboolean);

/*
 * Class:     com_example_testaudioandroid_VoiceSession
 * Method:    GetData
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_example_testaudioandroid_VoiceSession_GetData
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_example_testaudioandroid_VoiceSession
 * Method:    GetRoomMember
 * Signature: (ILjava/util/ArrayList;)I
 */
JNIEXPORT jint JNICALL Java_com_example_testaudioandroid_VoiceSession_GetRoomMember
  (JNIEnv *, jobject, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
